### ISSUE TITLE
Add port mappings for clients running outside the kind cluster

### ISSUE THREAD

**Issue by razvan** [stackabletech/integration-tests#85]
## The problem

`NodePort` services set up in kind clusters cannot be used unless ports are also exposed by Docker.

## Proposed solution

Expand the cluster configuration to expose Docker ports. Example taken from https://stackoverflow.com/a/62433164 :

```
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
- role: worker
```
